{% set version = "1.5.4" %}

package:
  name: pynio
  version: {{ version }}

source:
  url: https://github.com/NCAR/pynio/archive/{{ version }}.tar.gz
  sha256: e5bb57d902740d25e4781a9f89e888149f55f2ffe60f9a5ad71069f017c89e1a

build:
  number: 1
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy 1.14.*
    - g2clib 1.6.*
    - hdf4
    - hdf5
    - hdfeos2
    - hdfeos5
    - jasper
    - libgdal
    - libnetcdf
    - libuuid  # [osx]
    - proj4
  run:
    - python
    - numpy >=1.14
    - g2clib 1.6.*
    - hdf4
    - hdf5
    - hdfeos2
    - hdfeos5
    - jasper
    - libgdal
    - libnetcdf
    - libuuid  # [osx]
    - proj4

test:
  source_files:
    - test
    - ncarg
  requires:
    - nose
  imports:
    - Nio
  commands:
    - cd $SRC_DIR/test && nosetests  # [not win]

about:
  home: http://www.pyngl.ucar.edu/Nio.shtml
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'PyNIO is a multi-format data I/O package with a NetCDF-style interface.'

extra:
  recipe-maintainers:
    - marylhaley
    - ocefpaf
    - jhamman
    - david-ian-brown
    - khallock
