{% set version = "1.5.0beta" %}
{% set commit = "d6515e3dbda62deec7a3df949daf5755f88b5431" %}

package:
    name: pynio
    version: {{ version }}

source:
    fn: pynio-{{ version }}-{{ commit }}.tar.gz
    url: https://github.com/NCAR/pynio/archive/{{ commit }}.tar.gz
    sha256: 5ca3375b9f6984113c022275a098e648795d40b4a5181915e92807d6a25b6d25

build:
    number: 7
    skip: True  # [win or py3k]

requirements:
    build:
        - python
        - numpy x.x
        - libnetcdf 4.4.*
        - proj.4
        - gdal >=2.*
        - g2clib
        - hdfeos2
        - hdfeos5
        - gcc
        - isl 0.12.*
    run:
        - python
        - numpy x.x
        - libnetcdf 4.4.*
        - hdf4
        - proj.4
        - gdal >=2.*
        - g2clib
        - hdfeos2
        - hdfeos5
        - libgcc
        - isl 0.12.*

test:
    requires:
        - nose
    imports:
        - Nio
    commands:
        - cd $SRC_DIR/test && nosetests
        - conda inspect linkages -n _test pynio  # [linux]

about:
    home: http://www.pyngl.ucar.edu/Nio.shtml
    license: BSD-3-clause
    summary: PyNIO is a multi-format data I/O package with a NetCDF-style interface

extra:
    recipe-maintainers:
        - ocefpaf
        - jhamman
