{% set version = "1.5.5" %}

package:
  name: pynio
  version: {{ version }}

source:
  url: https://github.com/NCAR/pynio/archive/{{ version }}.tar.gz
  sha256: 045c8b2ee71f13f9b1164da6286b88e556a6519bc05485d4666bbab57d03caa0
  patches:
    - h5_use_110_api.patch

build:
  number: 13
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - g2clib 1.6.0
    - hdf4
    - hdf5
    - hdfeos2
    - hdfeos5
    - jasper
    - libgdal
    - libnetcdf
    - libuuid  # [osx]
    - proj
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - g2clib 1.6.0
    - hdf4
    - hdf5
    - hdfeos2
    - hdfeos5
    - jasper
    - libgdal
    - libnetcdf
    - libuuid  # [osx]
    - proj

test:
  source_files:
    - test
    - ncarg
  requires:
    - pytest
  imports:
    - Nio
  commands:
    - cd $SRC_DIR/test && pytest -k "not test_opendap2"  # [not win]

about:
  home: http://www.pyngl.ucar.edu/Nio.shtml
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'PyNIO is a multi-format data I/O package with a NetCDF-style interface'

extra:
  recipe-maintainers:
    - marylhaley
    - ocefpaf
    - jhamman
    - david-ian-brown
    - khallock
